config/routes.rb
Rails.application.routes.draw do
  resources :beers
  resources :companies, only: %i[index show]

  root to: "companies#index"

  # DSL - Domain Specific Language for Routing! Yay!

  # GET /companies        =>   companies#index   (Load and display all companies)
  # get "/companies", to: "companies#index", as: "companies" # companies_path

  # GET /companies/:id    =>   companies#show    (Load and display a single company by id)
  # get "/companies/:id", to: "companies#show", as: "company", constraints: { id: /\d+/ } # company_path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :company

  validates :name, :price, :description, presence: true
  validates :price, numericality: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :beers, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[show edit update destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.includes(:company).all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show; end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit; end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: "Beer was successfully created." }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: "Beer was successfully updated." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: "Beer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # DRY - Don't Repeat Yourself
  def set_beer
    @beer = Beer.includes(:company).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_params
    params.require(:beer).permit(:name, :price, :description)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all # Using our Company model to load all companies from the db.
  end
  # Automagically load app/views/companies/index.html.erb

  def show
    @company = Company.find(params[:id])
  end
  # Automagically load app/views/companies/show.html.erb
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/beers/_form.html.erb
<%= form_with(model: beer, local: true) do |form| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %> brewed by <%= beer.company.name %></td>
        <td><%= number_to_currency beer.price %></td>
        <td><%= beer.description %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @beer.name %>
</h1>

<p>
  <%= @beer.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @beer.price %>
</p>

<p>
  Brewed by <%= link_to @beer.company.name, company_path(@beer.company) %>.
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/companies/index.html.erb
<h1>All Companies</h1>
<ul>
  <% @companies.each do |company| %>
    <li><%= link_to company.name, company %></li>
  <% end %>
</ul>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p>This brewery produces <%= @company.beers.count %> beers.</p>

<h2>Beers</h2>
<ul>
  <% @company.beers.each do |beer| %>
    <li><%= link_to beer.name, beer %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beers On Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Beers on Rails</h1>
      <nav>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Beers', beers_path %></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>